// <auto-generated />
using System;
using BookVaultApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookVaultApi.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20260912163048_NewDataAdded")]
    partial class NewDataAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookVaultApi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Paulo Coelho",
                            PublicationDate = new DateTime(1988, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quote = "When you want something, all the universe conspires in helping you to achieve it.",
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            PublicationDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quote = "Big Brother is watching you.",
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Harper Lee",
                            PublicationDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quote = "You never really understand a person until you consider things from his point of view.",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 4,
                            Author = "F. Scott Fitzgerald",
                            PublicationDate = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quote = "So we beat on, boats against the current, borne back ceaselessly into the past.",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Jane Austen",
                            PublicationDate = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quote = "It is a truth universally acknowledged.",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.R.R. Tolkien",
                            PublicationDate = new DateTime(1937, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quote = "Not all those who wander are lost.",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 7,
                            Author = "J.K. Rowling",
                            PublicationDate = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quote = "It does not do to dwell on dreams and forget to live.",
                            Title = "Harry Potter and the Philosopher's Stone"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Markus Zusak",
                            PublicationDate = new DateTime(2005, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quote = "I am haunted by humans.",
                            Title = "The Book Thief"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Antoine de Saint-Exupéry",
                            PublicationDate = new DateTime(1943, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quote = "What is essential is invisible to the eye.",
                            Title = "The Little Prince"
                        },
                        new
                        {
                            Id = 10,
                            Author = "James Clear",
                            PublicationDate = new DateTime(2018, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quote = "Every action you take is a vote for the person you wish to become.",
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 11,
                            Author = "James Clear",
                            PublicationDate = new DateTime(2018, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quote = "Every action you take is a vote for the person you wish to become.",
                            Title = "test"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
